# Generated by Django 3.1.2 on 2020-11-07 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_max_load',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
