# Generated by Django 3.1.2 on 2020-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201116_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(blank=True, choices=[('P', 'Passenger'), ('C', 'Cargo')], max_length=2, null=True),
        ),
    ]
