# Generated by Django 3.1.2 on 2020-11-30 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201126_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='health_state',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
