# Generated by Django 3.1.2 on 2020-10-28 10:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designated_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('N', 'Not started'), ('I', 'In progress'), ('F', 'Finished')], max_length=1, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
