# Generated by Django 3.1.2 on 2020-11-07 14:07

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_license_type'),
        ('routes', '0002_auto_20201028_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('N', 'Not started'), ('I', 'In progress'), ('F', 'Finished')], max_length=1, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_driver', to='users.driver')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='load_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='route',
            name='load_type',
            field=models.CharField(blank=True, choices=[('P', 'Passenger'), ('C', 'Cargo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('S', 'Standard'), ('L', 'Low')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Designated_Route',
        ),
        migrations.AddField(
            model_name='designatedroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='routes.route'),
        ),
    ]
