# Generated by Django 3.1.2 on 2020-11-07 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20201107_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='load_quantity',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
