# Generated by Django 3.1.2 on 2020-11-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20201107_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
