# Generated by Django 3.1.2 on 2020-11-26 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designatedroute',
            name='current_location',
        ),
        migrations.AddField(
            model_name='route',
            name='min_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='route',
            name='min_health',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
